modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Focamacho/RingsOfAscension/issues"
[[mods]]
modId="ringsofascension"
version="${file.jarVersion}"
displayName="Rings of Ascension"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension"
description='''
Rings of Ascension is a mod that uses the Curios API to add 20+ new rings to your minecraft. Each ring has its own special effect that is activated when the ring is equipped.

Rings from this mod don't have a recipe and can only be found in dungeon chests.
'''
[[dependencies.ringsofascension]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2,)"
    ordering="NONE"
    side="BOTH"